# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bEl-LWnxr9TdmDLATL3hLsvCAoHNDitx
"""

pip install alpha_vantage

from alpha_vantage.timeseries import TimeSeries

API_key = 'XXXXXXX'

ts = TimeSeries(API_key, output_format='pandas')
data = ts.get_daily('OZK')

data

data[0]